### ISSUE TITLE
After upgrade to 3.3.6 switch state of Teckin devices is not shown

### ISSUE THREAD

**Issue by xxcite** [Apollon77/ioBroker.tuya#187]
**Description**
Today I upgraded my tuya adapter from 3.2.3 to 3.3.6. I then observed that my visualization where I use the `switch_1` object does not work any longer. I can set `switch_1` to `true` or `false` and the device switches on and off but the status is not shown.

I tried to restart the instance, the ioBroker, downgraded the adapter to 3.2.3 but still the same issue.

**Expected behavior**  
`switch_1` switch object shows the status

**Versions:**  
 - Adapter version: 3.3.6 (3.2.3 after downgrade)
 - JS-Controller version: 2.2.9
 - Node version: v10.20.1
 - Operating system: raspbian

![grafik](https://user-images.githubusercontent.com/42863794/86530908-2e1d7400-bebd-11ea-88bb-79e5972280fc.png)

**Comment by Apollon77** [comment]
There was no change in this regard. Please provide debug log. Log of Adapter Start and also of a Switch via iobroker and via App (important: Start app AFTER iobroker connected to the device

**Comment by xxcite** [comment]
Hi @Apollon77,

thanks for your quick answer. Please find attached the adapter's ioBroker log. One thing I noticed is the following:
```
2020-07-05 17:31:24.954  - debug: tuya.0 (4127) bf57c089f6ee60b5ae9om5: Error from device (0): App still open on your mobile phone? json obj data unvalid
2020-07-05 17:31:24.954  - debug: tuya.0 (4127) bf57c089f6ee60b5ae9om5: Received data: {"1":null,"2":null,"3":null,"101":null,"102":null,"103":null}
```
I checked my mobile phone but the `Smart Life` app is definitely not running at all.

What do you exactly mean with "and also of a Switch via iobroker and via App (important: Start app AFTER iobroker connected to the device"?

BTW: The device is a Smart Plug.

[tuya-start.log](https://github.com/Apollon77/ioBroker.tuya/files/4875191/tuya-start.log)

Thanks

**Comment by Apollon77** [comment]
Did you any firmware update of the Teckin device? Is seems to be that the returned json from the device is not valid and so values can not be parsed.

**Comment by xxcite** [comment]
I didn‘t do any update on the devices. I have 4 of those smart plugs and the same issue with all of them. I have also 2 other older Gosund devices that still work perfectly.

**Comment by Kenny369** [comment]
I have the same error
If i change the switch-state to true it shows this for 1 sec and after this its an empty field. It didn't hold the state

Tuya Adapter version: 3.3.6 
JS-Controller version: 3.1.6
Node version: v10.21.1
Operating system: raspbian

**Comment by xxcite** [comment]
That's exactly the same behavior that I observed ...

**Comment by Apollon77** [comment]
That the values gets "emptied" is because of the fact that after the change the device seems to senda respeose which is invalid and thats why it is overwritten as "null"

**Comment by Apollon77** [comment]
Also die Ursache scheint wohl das zu sein: https://github.com/codetheweb/tuyapi/pull/321#issue-417672411
bzw https://github.com/codetheweb/tuyapi/issues/246#issuecomment-526259164

Scheinbar sendet das Gerät etwas ungültiges als Ergebnis des Schaltbefehls zurück ... 

Ok, ich versuche mal was zu bauen um da drum herum zu arbeiten

**Comment by Apollon77** [comment]
Bitte installiert mal vom Github (Versionsnummer bleibt gleich wie letzte 3.3.7). Dann bitte sowohl log vom start wie auch einer Schaltaktion als Debug.

Es scheint so zu sein das Euer Device auf "get" Anfragen nicht korrekt antwortet. Heisst aber auch das der Adapter in dem Fall nur die Daten bekommt die das Gerät aktiv "pusht" ... er kann Sie nicht aktualisieren. Das müsste aber auch schon davor so gewesen sein ... Das log sollte das jetzt zeigen.

**Comment by xxcite** [comment]
Shall we switch to German now?

**Comment by Apollon77** [comment]
:))) Both ok for me

**Comment by sync85** [comment]
scheint zu laufen :) hatte mit meiner LSC Smart Connect von Action das gleiche Problem. Nach dem Github update geht es wieder! Also behaupte ich wir sind auf dem richtigen weg :)

**Comment by Apollon77** [comment]
Ein log wäre dennoch cool um zu sehen das es sich so verhält wie gewollt.

**Comment by sync85** [comment]
muss schauen wie ich das mit debug mache so sieht es bei mir beim start aus:

tuya.0 | 2020-07-08 07:03:15.325 | info | (10444) bfddb46624b6c34ca2hnrr Init with IP=192.168.0.24, Key=002e4adc2b3c64b4, Version=3.3
-- | -- | -- | --
tuya.0 | 2020-07-08 07:03:15.295 | info | (10444) 70770354c44f33ad0ec1: None of the discovered devices matches :-(
tuya.0 | 2020-07-08 07:03:15.293 | info | (10444) 08207108600194cbf402: None of the discovered devices matches :-(
tuya.0 | 2020-07-08 07:03:15.084 | info | (10444) Listen for encrypted local Tuya devices on port 6667
tuya.0 | 2020-07-08 07:03:15.083 | info | (10444) Listen for local Tuya devices on port 6666
tuya.0 | 2020-07-08 07:03:15.070 | info | (10444) Existing devices initialized
tuya.0 | 2020-07-08 07:03:15.067 | info | (10444) 70770354c44f33ad0ec1 Init with IP=192.168.0.65, Key=12b5cfda96e3bb02, Version=3.3
tuya.0 | 2020-07-08 07:03:15.059 | info | (10444) 08207108600194cbf402 Init with IP=192.168.0.26, Key=cd3888c830c71530, Version=3.3
tuya.0 | 2020-07-08 07:03:15.022 | info | (10444) bfddb46624b6c34ca2hnrr Init with IP=192.168.0.24, Key=002e4adc2b3c64b4, Version=3.3
tuya.0 | 2020-07-08 07:03:14.466 | info | (10444) starting. Version 3.3.7 in /opt/iobroker/node_modules/iobroker.tuya, node: v10.21.0, js-controller: 3.1.4
tuya.0 | 2020-07-08 07:03:14.400 | info | (10444) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system

das ist die Lampe die vorher gesponnen hatte: bfddb46624b6c34ca2hnrr
jetzt geht diese wieder.

hoffe das hilft etwas geh später sonst nochmal schauen wegen debug output :)

**Comment by xxcite** [comment]
Mit der Version von Github scheint es erstmal auch mit meinen Teckin SP22 Devices wieder zu tun. Funktioniert hat es aber erst, nachdem ich von ioBroker aus einmal geschaltet habe. Ich hoffe, ich habe die Logs richtig gemacht ;-)

[tuya-start-github.log](https://github.com/Apollon77/ioBroker.tuya/files/4888791/tuya-start-github.log)
[tuya-switch-github.log](https://github.com/Apollon77/ioBroker.tuya/files/4888792/tuya-switch-github.log)

Vielen Dank :-)

**Comment by Apollon77** [comment]
Also log sieht ok aus. Ja im Debug logt er die "Nulls" (das ist das was bei dem "unvalid obj json" zurückkommt und loggt dasnn das "ignore" und damit wird einfach nichts gesetzt. ok baue spter die version offiziell. Danke fürs Testen!

**Comment by Apollon77** [comment]
> Funktioniert hat es aber erst, nachdem ich von ioBroker aus einmal geschaltet habe. Ich hoffe, ich habe die Logs richtig gemacht ;-)

Ein Adapter restart hätte ggf gereicht ... das ist manchmal nötig bei GitHub installs

**Comment by xxcite** [comment]
> Ein Adapter restart hätte ggf gereicht ... das ist manchmal nötig bei GitHub install

Hatte ich natürlich zuerst probiert, hat aber nicht funktioniert ;-)

**Comment by Apollon77** [comment]
3.3.8 geht auf npm und ist morgen im latest
