### ISSUE TITLE
Are the devices connected to China-Cloud?

### ISSUE THREAD

**Issue by necotec** [Apollon77/ioBroker.tuya#220]
Hello,

A very cool Project. But there is a question for me. When I've connected my devices to the iobroker.tuya adaptor, is there a connection to the China-Cloud too?

Thank you

Have a great day

necotec

**Comment by Apollon77** [comment]
The devices are connected to their cloud and they also need for the initial sync. After that you could block that access because  the adapter itself only connects to their local interface ... but the adapter have no control over what the devices themsekf do. It is up to you to block access to the Tuya cloud if you want. BUT: There are also some devices reported that react unexpectedly/unstable when you block this access ...
