### ISSUE TITLE
Power sockets losing connection/sync

### ISSUE THREAD

**Issue by derherrgraf** [Apollon77/ioBroker.tuya#257]
**Describe the bug**  
For a week now my sockets keep losing their connection. It is completely random which ones and how many. Everything worked perfectly so far.
the problem is that i can set the status to on and off. this also changes but it does not affect the socket.
I have added the only line that can be found in the log file (one for each socket).

If this is duplicated, please link this issue (i read through a few issues but they didn't really reflect my problem)

**Screenshots & Logfiles**  
Example Line (every Socket show the same)
`2021-02-22 10:11:08.899 - warn: tuya.0 (8661) ID error on get: connect ENETUNREACH IP:6668 - Local (0.0.0.0:0)`

**Versions:**  
 - Adapter version: 3.5.6
 - JS-Controller version: 3.2.16
 - Node version: 14.15.3
 - Operating system: rasbian

**Additional context**

**Comment by derherrgraf** [comment]
jetzt grade bemerkt und im log gefunden:

```
tuya.0 | 2021-02-23 13:11:43.110 | error | (4823) ID: connection timed out
tuya.0 | 2021-02-23 13:10:25.237 | error | (4823) ID: connection timed out
```

**Comment by Apollon77** [comment]
ENETUNREACH means that the device is not reachable on network level and "connection timed out "means that the device is not responding anymore.

If these are battery powered devices then please read readme again because they are not supported because they are not online long enough.

If not battery then honestly: check wlan connectivity, try to power off/on the defines ... And yes thre are also devices known where the "local port" implementation is bullshit and ega buggy and disconnect very often or such ... sorry the adapter can not help anything here.

**Comment by derherrgraf** [comment]
Ach komm auf englisch ist mir das jetzt zu blöd :D
Das sind Steckdosen als rund um die Uhr online. Das ganze ist auch erst seit ca. einer Woche und davor hatte ich 0 Probleme daher dieser Report. Ein Adapter restart hilft eig immer, aber das das ist ja nicht wirklich eine Lösung. Könnte das ggf. mit #242 zusammenhängen? Es sind nämlich genau diese Plugs die ich verwende. Oder könnte es auch an der Vielzahl der Plugs liegen? Hab sicher 20 inzwischen im Einsatz.

**Comment by Apollon77** [comment]
Abhängigkeit zu dem Issue sehe ich eher nicht ... Wie gesagt ...grund keine Ahnung.mach die Steckdose mal Stromlos ... ich hatte solche die alle paar Wochen mal einen restart brauchten.
